git:
  extensions:
    shallow_clone: true
clean_workspace: true
builders:
  - docker
docker_name: eduid/eduid-html
managed_scripts:
  - docker_build_prep.sh
  - docker_tag.sh
triggers:
  cron: "@weekly"
upstream:
  - eduid-front
  - eduid-managed-accounts
slack:
  room: eduid-builds
clean_workspace: true
